// IMPORTS 
// React 
import { useState, useEffect } from "react"
// Styles 
import "./GamePage.css"
// Word exists
import wordExists from 'word-exists';



// COMPONENTS 
export const GamePage = () => {

    // LOGIC 

    // GENERATED BY BACK END
    const [generatedString, setGeneratedString] = useState(
        [' ', ' ', ' ', 'T', 'E', ' ', 'N',
            'F', ' ', 'N', 'T', ' ', 'S', 'Y',
            ' ', 'A', 'R', ' ', 'E', 'S', ' ',
            'J', ' ', 'U', 'R', ' ', 'E', 'Y',
            'P', ' ', 'S', 'S', ' ', 'O', 'N',
            'R', ' ', 'G', 'I', ' ', 'E', 'N',
            ' ', 'O', ' ', 'I', 'E', ' ', 'Y'])

    // COMPLETED WORDS ARRAY 
    const [completedWords, setCompletedWords] = useState([])

    // STRING CHAR COUNT (Start at 0 finish at 48)
    const [stringCharCount, setStringCharCount] = useState(0)

    //USER INPUT
    const [userInput, setUserInput] = useState([])
    console.log("userInput word" + userInput)


    // LETTER PRESS FUNCTION
    const letterPressFunction = (e) => {
        if (stringCharCount >= 48) {
            return;
        }
        const inputtedLetter = e.target.innerHTML
        // If generatedString[stringCharCount] is " " then add that letter to current word array
        if (generatedString[stringCharCount] === " ") {
            setStringCharCount(prevCount => prevCount + 1);
            setUserInput(prevArr => [...prevArr, inputtedLetter]);
            console.log(userInput)
        } else {
            const exclusiveLetter = generatedString[stringCharCount];
            if (exclusiveLetter === inputtedLetter) {
                setStringCharCount(prevCount => prevCount + 1);
                setUserInput(prevArr => [...prevArr, inputtedLetter]);
                console.log(userInput)
            } else {
                console.group("only letter " + generatedString[stringCharCount] + " can go here")
                return;
            }
        }
    };

    // DELETE PRESS FUNCTION 
    const deletePressFunction = () => {
        if (stringCharCount <= 0) {
            return;
        }
        setStringCharCount(prevCount => prevCount - 1);
        setUserInput(prevArr => prevArr.slice(0, -1));
    }

    // ENTER KEYPRESS
    const enterKeyPress = () => {

        console.log(wordExists("Hello"))
    }










    // RETURN
    return (
        <div className="GamePage">
            <div className="Title">
                <div className="Title-Box-Black">
                    4
                </div>
                <div className="Title-Box-Black">
                    9
                </div>
                <div className="Title-Box-White">
                    L
                </div>
                <div className="Title-Box-White">
                    E
                </div>
                <div className="Title-Box-White">
                    T
                </div>
                <div className="Title-Box-White">
                    T
                </div>
                <div className="Title-Box-White">
                    E
                </div>
                <div className="Title-Box-White">
                    R
                </div>
                <div className="Title-Box-White">
                    S
                </div>
            </div>

            <div className="Top-Section">
                <div className="Top-Section-Left">
                    <div className="Top-Section-Left-Word-Container">
                        <div className="Top-Section-Left-Word-Box">
                            H
                        </div>
                        <div className="Top-Section-Left-Word-Box">
                            E
                        </div>
                        <div className="Top-Section-Left-Word-Box">
                            L
                        </div>
                        <div className="Top-Section-Left-Word-Box">
                            L
                        </div>
                        <div className="Top-Section-Left-Word-Box">
                            O
                        </div>
                    </div>
                    <div className="Top-Section-Left-Word-Container">
                        <div className="Top-Section-Left-Word-Box">
                            H
                        </div>
                        <div className="Top-Section-Left-Word-Box">
                            E
                        </div>
                        <div className="Top-Section-Left-Word-Box">
                            L
                        </div>
                        <div className="Top-Section-Left-Word-Box">
                            L
                        </div>
                        <div className="Top-Section-Left-Word-Box">
                            O
                        </div>
                    </div>
                    <div className="Top-Section-Left-Word-Container">
                        <div className="Top-Section-Left-Word-Box">
                            H
                        </div>
                        <div className="Top-Section-Left-Word-Box">
                            E
                        </div>
                        <div className="Top-Section-Left-Word-Box">
                            L
                        </div>
                        <div className="Top-Section-Left-Word-Box">
                            L
                        </div>
                        <div className="Top-Section-Left-Word-Box">
                            O
                        </div>
                    </div>

                </div>
                <div className="Top-Section-Right">
                    <div className="Letter-Count">
                        17
                    </div>
                </div>
            </div>

            <div className="String-Section">



                <div className="String-Section-Current-Letter-Box-Border">
                    <div className="String-Section-Current-Letter-Box">
                        {generatedString[stringCharCount]}
                    </div>
                </div>



                <div className="String-Section-Letter-Box">
                    {generatedString[(stringCharCount + 1)]}
                </div>
                <div className="String-Section-Letter-Box">
                    {generatedString[(stringCharCount + 2)]}
                </div>
                <div className="String-Section-Letter-Box">
                    {generatedString[(stringCharCount + 3)]}
                </div>
                <div className="String-Section-Letter-Box">
                    {generatedString[(stringCharCount + 4)]}
                </div>
            </div>

            <div className="Current-Word-Section">

                {userInput.map((letter, index) => (
                    <div
                        key={index}
                        className="Current-Word-Section-Box">
                        {letter}
                    </div>
                ))}


            </div>

            {/* <button className="Add-Word-Button">
                Add Word
            </button> */}

            <div className="Keyboard">

                <div className="Keyboard-Row">
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">Q</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">W</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">E</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">R</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">T</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">Y</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">U</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">I</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">O</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">P</button>
                </div>

                <div className="Keyboard-Row">
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">A</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">S</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">D</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">F</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">G</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">H</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">J</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">K</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">L</button>
                </div>

                <div className="Keyboard-Row">
                    <button
                        onClick={deletePressFunction}
                        className="Special-Button"
                        style={{
                            backgroundColor: 'var(--Orange)'
                        }}
                    >Del</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">Z</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">X</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">C</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">V</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">B</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">N</button>
                    <button
                        onClick={letterPressFunction}
                        className="Keyboard-Button">M</button>
                    <button
                        onClick={enterKeyPress}
                        className="Special-Button"
                        style={{
                            backgroundColor: 'var(--Green)'
                        }}
                    >ENTR</button>
                </div>
            </div>
        </div>
    )
}